# Model

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm

In [2]:
df = pd.read_csv('../data/processed/squawk7700_processed_final_v1.csv')

In [3]:
df.head()

,flight_id,icao24,registration,typecode,origin,landing,destination,diverted,tweet_problem,tweet_result,...,avh_id,avh_problem,avh_result,avh_fueldump,airlineName,isFreighter,productionLine,ageYears,verified,manufacturer
0,ARG1511_20180101,e06442,LV-FQB,B738,SACO,SABE,SABE,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Aerolineas Argentinas,False,Boeing 737 NG,13.2,True,Boeing
1,DAL14_20180101,a14c29,N183DN,B763,KATL,NaN,EDDF,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Delta Air Lines,False,Boeing 767,31.6,True,Boeing
2,JBU263_20180108,aa600a,N768JB,A320,KJFK,NaN,KSEA,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,JetBlue Airways,False,Airbus A320,15.9,True,Airbus
3,DAL65_20180108,ab2855,N818NW,A333,KATL,KLAX,KLAX,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Delta Air Lines,False,Airbus A330,17.4,True,Airbus
4,EDW24_20180111,4b1901,HB-JMF,A343,LSZH,LSZH,MMUN,LSZH,engine,return,...,4b382175,engine,return,unknown,Edelweiss Air,False,Airbus A340,21.1,True,Airbus